my_app/urls.py
from django.urls import path, include
from my_app import views


app_name = 'my_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('regular_customer/', views.regular_customer, name='regular_customer'),
    path('site_admin/', views.site_admin, name='site_admin'),
    path('supplier/', views.supplier, name='supplier'),
    path('drugstore/', views.drugstore, name='drugstore'),
    path('add_product/', views.add_product, name='add_product'),
    path('add_user_product_admin/', views.add_user_product_admin, name='add_user_product_admin'),
    path('add_user_product_supplier/', views.add_user_product_supplier, name='add_user_product_supplier'),
    path('add_order_regualr_customer/', views.add_order_regular_customer, name='add_order_regular_customer'),
    path('search_order_view/', views.search_order_view, name='search_order_view'),
    path('search_order/', views.search_order, name='search_order'),
    path('search_movement_view/', views.search_movement_view, name='search_movement_view'),
    path('search_movement/', views.search_movement, name='search_movement'),
    path('get_form_info/', views.get_form_info, name='get_form_info'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('index_login/', views.index_login, name='index_login'),


]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_app.urls')),
]

my_app/forms.py
from attr import fields
from django import forms
from django.contrib.auth.models import User
from .models import SearchMovement, UserProfileInfo, Product, UserProfileInfoProduct, Order, DemandSupplyMovement, Movement, SearchOrder, SearchMovement
from functools import partial
from django.forms.widgets import DateInput
from django.db.models import Sum






class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email', 'password',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control', 'style':'width:400px'})
            


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('membership_type',) 

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control', 'style':'width:400px'})

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'produced_date', 'expired_date', 'company')
        widgets = {
            'produced_date': DateInput(attrs={'type': 'date'}),
            'expired_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field in self.fields:        
            self.fields[field].widget.attrs.update({'class':'form-control'})

    

class UserProfileProductForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfoProduct
        fields = '__all__'
        widgets = {
            'delivery_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, username=None, **kwargs):
        super(UserProfileProductForm, self).__init__(**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})

        if username:
            self.fields['user_profile_info'].queryset = User.objects.filter(username=username)    





class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        widgets = {
            'order_date': DateInput(attrs={'type': 'date'}),
        }


    def __init__(self, username=None, membership_list=None, **kwargs):
        super(OrderForm, self).__init__(**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'}) 
        self.fields['sequence'].widget.attrs.update({'class':'form-control','readonly':'readonly'}) 

        if username and membership_list:
            self.fields['destination'].queryset = User.objects.filter(username=username)
            self.fields['source'].queryset = UserProfileInfo.objects.filter(membership_type__in=membership_list).exclude(user__username=username)
            
            
            
            
            if Order.objects.order_by('-id'):   
                print(Order.objects.order_by('-id')[0].sequence)     
                self.fields['sequence'].initial = int(Order.objects.order_by('-id')[0].sequence) + 1 
            else:
                self.fields['sequence'].initial = 1000

            # data = super(OrderForm, self).clean()
            # print(data.get('source'))
            # print(self.fields['product'])
            # source = UserProfileInfo.objects.get(user=self.fields['source'])
            # product = Product.objects.get(name=self.fields['product'])
            # self.fields['quantity'].initial = Movement.objects.filter(destination=self.fields['source'].value()).filter(product=current_product).aggregate(Sum('remain_quantity'))['remain_quantity__sum']
            # print(Movement.objects.filter(destination=current_source).filter(product=current_product).aggregate(Sum('remain_quantity'))['remain_quantity__sum'])
                





class MovementForm(forms.ModelForm):
    class Meta:
        model = Movement
        fields = '__all__'
        widgets = {
            'movement_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(MovementForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})    



class DemandSupplyMovementForm(forms.ModelForm):
    class Meta:
        model = DemandSupplyMovement
        fields = '__all__' 

    def __init__(self, *args, **kwargs):
        super(DemandSupplyMovementForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})         




class SearchOrderForm(forms.ModelForm):
    class Meta:
        model = SearchOrder
        fields = ('sequence', 'product', 'source', 'destination', 'start_date', 'end_date')
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(SearchOrderForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})    

        

class SearchMovementForm(forms.ModelForm):
    class Meta:
        model = SearchMovement
        fields = ('product', 'sequence', 'source', 'destination', 'start_date', 'end_date')
        widgets = {
            'start_date': DateInput(attrs={'type': 'date'}),
            'end_date': DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(SearchMovementForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})    






          

my_app/views.py
from msilib import sequence
import re
from unicodedata import name
from django.shortcuts import render, HttpResponse
from django.core import serializers
from itsdangerous import json

from numpy import product, source
from .forms import UserForm, UserProfileForm, ProductForm, UserProfileProductForm, OrderForm, User, SearchOrderForm, SearchMovementForm
from .models import SearchMovement, UserProfileInfo, Product, UserProfileInfoProduct, Order, Movement, DemandSupplyMovement, SearchOrder
from django.db.models import Sum, Q

from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.http import JsonResponse




def index(request):
    context = {}
    return render(request, 'my_app/index.html', context)

def index_login(request):
    user_obj = UserProfileInfo.objects.filter(user__username=request.user.username)
    membership_type = user_obj[0].membership_type
    context = {'membership_type':membership_type}
    return render(request, 'my_app/index_login.html', context)



def register(request):
    registered = False

    if request.method == 'POST':
        
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()  

            profile = user_profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True

    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()
    return render(request,'my_app/registration.html',
                 {'user_form':user_form,
                 'user_profile_form':user_profile_form,
                 'registered':registered
                 })
                 

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                # print(UserProfileInfo.objects.all())
                user_obj = UserProfileInfo.objects.filter(user__username=username)
                membership_type = user_obj[0].membership_type

                if membership_type == 'regular_customer':
                    return HttpResponseRedirect(reverse('my_app:regular_customer'))
                elif membership_type == 'site_admin':
                    return HttpResponseRedirect(reverse('my_app:site_admin'))
                elif membership_type == 'supplier':
                    return HttpResponseRedirect(reverse('my_app:supplier'))
                elif membership_type == 'drugstore':
                    return HttpResponseRedirect(reverse('my_app:drugstore'))        

                else:
                    return HttpResponse('Please check the code!')    
            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE')
        else:
            return HttpResponse('Invalid login details supplied') 
 

    else:
        return render(request,'my_app/login.html', {}) 


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('my_app:index'))


@login_required
def site_admin(request):
    product_form = ProductForm()
    product_list = Product.objects.order_by('id')
    user_profile_list = UserProfileInfo.objects.order_by('id')
    user_profile_product_form = UserProfileProductForm()
    user_profile_product_list = UserProfileInfoProduct.objects.order_by('id')
    movement_list = Movement.objects.order_by('id')
    demand_supply_movement_list = DemandSupplyMovement.objects.order_by('id')



    context = {'product_form':product_form, 'product_list':product_list,
               'user_profile_list':user_profile_list,
               'user_profile_product_form': user_profile_product_form, 'user_profile_product_list':user_profile_product_list,
               'movement_list':movement_list, 'demand_supply_movement_list':demand_supply_movement_list}
    return render(request, 'my_app/site_admin.html', context)



@login_required
def regular_customer(request):
    user_obj = UserProfileInfo.objects.filter(user__username=request.user.username)
    membership_type = user_obj[0].membership_type
    order_form = OrderForm(username=request.user.username, membership_list=['drugstore'])        
    order_list = Order.objects.filter(destination=request.user.id)
    context = {'order_form':order_form, 'order_list':order_list,'membership_type':membership_type}
    return render(request, 'my_app/regular_customer.html', context)








@login_required
def drugstore(request):  
        order_form = OrderForm(username = request.user.username, membership_list=['supplier', 'drugstore'])
        order_list = Order.objects.filter(destination=request.user.id).order_by('id')
        movement_list = Movement.objects.filter(Q(source=request.user.id) | Q(destination=request.user.id)).order_by('id')
        user_obj = UserProfileInfo.objects.filter(user__username=request.user.username)
        membership_type = user_obj[0].membership_type
        context = {'order_form':order_form, 'order_list':order_list,'movement_list':movement_list,'membership_type':membership_type}                      
        return render(request, 'my_app/drugstore.html', context) 


def search_movement_view(request):
    search_movement_form = SearchMovementForm()
    user_obj = UserProfileInfo.objects.filter(user__username=request.user.username)
    membership_type = user_obj[0].membership_type
    context = {'search_movement_form':search_movement_form,'membership_type':membership_type}                       
    return render(request, 'my_app/search_movement.html', context)


@login_required
def search_movement(request):
    if request.method == 'POST':
        search_movement_form = SearchMovementForm(data=request.POST)
        if search_movement_form.is_valid():
            search_movement = search_movement_form.save(commit=True)
            search_movement.save()
            
            search_movement_obj = search_movement
            sequence = Order.objects.get(sequence=search_movement_obj.sequence)
            search_movement_result = Movement.objects.filter(movement_date__range=[search_movement_obj.start_date,search_movement_obj.end_date],
                                                                 source=search_movement_obj.source,destination=search_movement_obj.destination,
                                                                 product=search_movement_obj.product,order=sequence) 
            # print(search_movement_result)
            ser_search_movement_list = []
            if search_movement_result:
                for instance in search_movement_result:
                    ser_instance = serializers.serialize('json', [instance,])
                    ser_search_movement_list.append(ser_instance)

                demand_supply_movement_obj = DemandSupplyMovement()
                result_trace_back=demand_supply_movement_obj.trace_back(demand_movement_list=search_movement_result,movement_result=[])
                ser_result_trace_back =[serializers.serialize('json', [trace_back,]) for trace_back in result_trace_back]
                                                     
                print(ser_search_movement_list)                         
                print(ser_result_trace_back) 
                                                                                                                                   
            else:
                ser_search_movement_list = []
                ser_result_trace_back = []

            return JsonResponse({'ser_search_movement_list':ser_search_movement_list, 'ser_result_trace_back':ser_result_trace_back}, status=200)
        else:
            return JsonResponse({"error": search_movement_form.errors}, status=400)
    else:
        return JsonResponse({'success':False}, status=400)     



def search_order_view(request):
    search_order_form = SearchOrderForm()
    user_obj = UserProfileInfo.objects.filter(user__username=request.user.username)
    membership_type = user_obj[0].membership_type

    context = {'search_order_form':search_order_form,'membership_type':membership_type}    
    return render(request, 'my_app/search_order.html', context)                                            


@login_required
def search_order(request):
    if request.method == 'POST':
        search_order_form = SearchOrderForm(data=request.POST)
        if search_order_form.is_valid():
            search_order = search_order_form.save(commit=True)
            search_order.save()
   
            search_order_obj = search_order
            print(search_order_obj )
            print(search_order_obj.product)
           
            search_order_result = Order.objects.filter(sequence=search_order_obj.sequence,product=search_order_obj.product,
                                                        source=search_order_obj.source, destination=search_order_obj.destination,
                                                        order_date__range=[search_order_obj.start_date,search_order_obj.end_date])
            if search_order_result:                                      
                print(search_order_result)
                ser_search_order_result = []
                for instance in search_order_result:

my_app/templates/my_app/base.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href = "{% static 'css/style.css' %}">



<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block head %}
{% endblock %}



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.css"/>
<link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel = "stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">

 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src = "https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src = "https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script src="{% static 'js/regular_customer.js' %}"></script>

{% block style %}

{% endblock %}





</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand-base" style="color:white" href="{% url 'my_app:index_login' %}">Home Page</a></li>
                <!-- <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin Page</a></li> -->
                <li class="nav-item"><a class="nav-link" style="color:white" href="{% url 'my_app:search_order_view' %}">Search Order Page</a></li>
                <li class="nav-item"><a class="nav-link" style="color:white" href="{% url 'my_app:search_movement_view' %}">Search Movement Page</a></li> 
            </ul>

            
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }} ({{ membership_type }}) 
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item"  href="{% url 'my_app:user_logout' %}">Logout</a>
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="#">Help</a>
                </div>
            </div>    

            <!-- <a class="dropdown-toggle" href="#">{{ user.username }}({{ membership_type }})</a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{% url 'my_app:user_logout' %}">Logout</a></li>
                </ul> -->
            

            
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        
        {% endblock %}
    </div>

{% block script %}
{% endblock %}
</body>
</html>



my_app/templates/my_app/drugstore.html
<!DOCTYPE html>
{% extends 'my_app/base.html' %}
{% block head %}
<title>Drugstore</title>
{% endblock %}



{% block body_block %}


<div class="container">
    <p>Please Order a Product</p>
    <form id="order_form" method="POST">
        {% csrf_token %}
        {{ order_form.as_p }}
        <label for="maximum_quantity">Maximum Quantity</label>
        <br>
        <input class="form-control readonly" type="text" name="" id="maximum_quantity" readonly>
        <br>
        
        <input class="btn" type="submit" value="Create an Order" name="order_submit">
    </form>
    <br>
    <br>
</div>


{% if order_list %}
    <div class="container">        
        <table id="order_info" class="table">
            <thead>
                <th>ID</th>
                <th>Order Sequence</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Order Date</th>
                <th>Source Warehouse</th>
                <th>Destination Warehouse</th>
            </thead>
            {% for order in order_list %}
            <tbody>
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.sequence }}</td>
                    <td>{{ order.product }}</td>
                    <td>{{ order.quantity }}</td>
                    <td>{{ order.order_date | date:'Y-m-d' }}</td>
                    <td>{{ order.source }}</td>
                    <td>{{ order.destination }}</td>
                </tr>
            </tbody>

            {% endfor %}
        </table>
    </div>
{% endif %}


{% if movement_list %}
    <div class="container">
        <p>Your Movement List</p>        
        <table id="movement_info" class="table">
            <thead>
                <th>ID</th>
                <th>Quantity</th>
                <th>Remain Quantity</th>
                <th>Movement Date</th>
                <th>Product</th>
                <th>Order</th>
                <th>Source Warehouse</th>
                <th>Destination Warehouse</th>
            </thead>
            {% for movement in movement_list %}
            <tbody>
                <tr>
                    <td>{{ movement.id }}</td>
                    <td>{{ movement.quantity }}</td>
                    <td>{{ movement.remain_quantity }}</td>
                    <td>{{ movement.movement_date }}</td>
                    <td>{{ movement.product }}</td>
                    <td>{{ movement.order }}</td>
                    <td>{{ movement.source }}</td>
                    <td>{{ movement.destination }}</td>
                </tr>
            </tbody>

            {% endfor %}
        </table>
    </div>
{% endif %}
{% endblock %}


{% block script %}

<script type="text/javascript">
    $(document).ready(function(){
        $('#order_form').change(function(e){
            e.preventDefault();

            var serializedData = $(this).serialize();
            $.ajax({
                type: 'GET',
                url: "{% url 'my_app:get_form_info' %}",
                data: serializedData,
                success: function(response){
                    
                    
                    // var ser_current_inventory = JSON.parse(response['ser_current_inventory']);
                    // alert(ser_current_inventory)
                    
                    var current_inventory_fields = response['ser_current_inventory']['current_inventory'];
                    
                    

                    $('#maximum_quantity').val(current_inventory_fields)                                     
                },
                error: function(response){
                    console.log(response)
                }
            });            
        });
    });



    $(document).ready(function(){
        $('#order_form').submit(function(e){
            e.preventDefault();

            var serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url: "{% url 'my_app:add_order_regular_customer' %}",
                data: serializedData,
                success: function(response){
                    $('#order_form').trigger('reset');

                    var ser_order = JSON.parse(response['ser_order']);
                    var order_fields = ser_order[0]['fields'];
                    
                    var ser_movement = JSON.parse(response['ser_movement'])
                    var movement_fields = ser_movement[0]['fields'];

                    $('#order_info tbody').prepend(
                        `<tr>
                        <td>${order_fields["id"]||""}</td>
                        <td>${order_fields["sequence"]||""}</td>
                        <td>${order_fields["product"]||""}</td>
                        <td>${order_fields["quantity"]||""}</td>
                        <td>${order_fields["order_date"]||""}</td>
                        <td>${order_fields["source"]||""}</td>
                        <td>${order_fields["destination"]||""}</td>
                        
                        </tr>`
                    )
                    $('#movement_info tbody').prepend(
                        `<tr>
                        <td>${movement_fields["id"]||""}</td>
                        <td>${movement_fields["quantity"]||""}</td>
                        <td>${movement_fields["remain_quantity"]||""}</td>
                        <td>${movement_fields["movement_date"]||""}</td>
                        <td>${movement_fields["product"]||""}</td>
                        <td>${movement_fields["order"]||""}</td>
                        <td>${movement_fields["source"]||""}</td>
                        <td>${movement_fields["destination"]||""}</td>
                        </tr>`
                    )
                    location.reload();                                        
                },
                error: function(response){
                    console.log(response)
                }
            });            
        });
    });


    $(document).ready(function(){

    })

</script>





{% endblock %}



my_app/templates/my_app/index_login.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href = "{% static 'css/style.css' %}">
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/d711256a25.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" style="color:white" href="{% url 'my_app:index_login' %}">Home Page</a></li>
                <!-- <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin Page</a></li> -->
                <li class="nav-item"><a class="nav-link" style="color:white" href="{% url 'my_app:search_order_view' %}">Search Order Page</a></li>
                <li class="nav-item"><a class="nav-link" style="color:white" href="{% url 'my_app:search_movement_view' %}">Search Movement Page</a></li> 
            </ul>

            
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }} ({{ membership_type }}) 
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item"  href="{% url 'my_app:user_logout' %}">Logout</a>
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="#">Help</a>
                </div>
            </div>    

            <!-- <a class="dropdown-toggle" href="#">{{ user.username }}({{ membership_type }})</a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{% url 'my_app:user_logout' %}">Logout</a></li>
                </ul> -->
            

            
        </div>
    </nav>
  
  <section id="title">
    <div class="container-fluid">
      <div class="row">

        <div class="left-row col-lg-6">
          <div class="login_index_text">
              <h1>Manange your drug warehouses via Drugstore Management System</h1>
              <ul>
                <li>Keep track of all shipments ...</li>
                <li>Getting informed about updated inventory ...</li>
                <li>Manage inventory in terms of drugstore and drug...</li>
              </ul>
          </div>
        </div>  
        
        <div class="pic1-image col-lg-6">
            <img class="image-class" src="{% static 'image/pic1.png' %}" alt="pic1-image">
        </div>
      </div>
    </div>
  </section>
    
      <section class="cta">
        <h1>Make sure all you need to keep healthy and refresh is available!</h1>
        <button type="button" class="btn btn-dark btn-lg download-button"><i class="fab fa-apple"></i> Download</button>
        <button type="button" class="btn btn-outline-light btn-lg download-button"><i class="fab fa-google-play"></i>Download</button>
      </section>
    
      <footer id="footer">
        <i class="social-icon fab fa-linkedin"></i>
        <p>© Copyright Morteza_Pouresmaeeli</p>
      </footer>



</body>
</html>











  
  



    
  